const PREFIX = "MovieDetails";

export const GET_MOVIE_DETAILS_REQUEST = `${PREFIX}/GET_MOVIE_DETAILS_REQUEST`;
export const GET_MOVIE_DETAILS_SUCCESS = `${PREFIX}/GET_MOVIE_DETAILS_SUCCESS`;
export const GET_MOVIE_DETAILS_FAILURE = `${PREFIX}/GET_MOVIE_DETAILS_FAILURE`;
